export default {
  CHANGE_HEADER: 'CHANGE_HEADER',
  CHANGE_CLASSES: 'CHANGE_CLASSES',
  TOGGLE_ADD_MODEAL_SHOW: 'TOGGLE_ADD_MODEAL_SHOW',
  UNSHIFT_MONEY_LIST: 'UNSHIFT_MONEY_LIST',
  RMEOVE_MONEY_ITEM: 'RMEOVE_MONEY_ITEM',
  CHANGE_TODAY: 'CHANGE_TODAY',
  CHANGE_RANGE: 'CHANGE_RANGE',
  CHANGE_TITLE_DATE: 'CHANGE_TITLE_DATE',
  CHANGE_DATEPICKER_SHOW: 'CHANGE_DATEPICKER_SHOW',
}
